In [1]:
import numpy as np
import pandas as pd
import nibabel as nb
import hypertools as hyp
import pickle
import os
import joblib
import neurosynth as ns
from scipy.spatial.distance import cdist
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
annot_dir = '../../data/annotations_dfs/'
ep_model_dir = '../../data/models/episodes/'
ep_traj_dir = os.path.join(ep_model_dir, 't100_w50/', 'trajectories')
ep_seg_dir = os.path.join(ep_model_dir, 't100_w50/', 'events')
ep_emb_dir = os.path.join(ep_model_dir, 't100_w50/', 'embeddings', 'k:1000')
rec_model_dir = '../../data/models/participants/'
rec_traj_dir = os.path.join(rec_model_dir, 'trajectories')
rec_seg_dir = os.path.join(rec_model_dir, 'events', 'k:1000')
rec_emb_dir = os.path.join(rec_model_dir, 'embeddings', 'k:1000')
pickle_dir = '../../data/pickles/'
braindata_dir = '../../data/brains/'
fig_dir = '../../figures/'
brainfig_dir = os.path.join(fig_dir,'brains/')

In [3]:
decoder = joblib.load(braindata_dir+'neurosynth_decoder.joblib')

In [5]:
# transform from pycortex space to MNI space
s1_to_mni = np.load(braindata_dir+'mni_xfm.npy')

# topic dimension voxel weights
episode_topic_voxweights = {ep : np.load(os.path.join(braindata_dir, ep, 'topic_voxelweights.npy'))
                            for ep in ['atlep1','atlep2','arrdev']}

# pycortex mask
mask = np.load(braindata_dir+'mask.npy')

In [6]:
def standardize_brainspace(vol, xfm=s1_to_mni):
    mni_space = cortex.mni.transform_to_mni(vol, xfm)
    std_brain = se.helpers._std((2,2,2))
    res_mni = nl.image.resample_img(mni_space, target_affine=std_brain.affine, target_shape=std_brain.shape)
    return res_mni

In [3]:
# ns_datset = ns.Dataset('../neurosynth/data/database.txt', feature_filename='../neurosynth/data/features.txt')
# ns_dataset.save(pickle_dir+'neurosynth_dataset.p')
# ns_dataset = ns.base.dataset.Dataset.load(pickle_dir+'neurosynth_dataset.p')

In [6]:
# decoder = ns.analysis.decode.Decoder(ns_dataset)
# joblib.dump(decoder, braindata_dir+'neurosynth_decoder.joblib')

In [56]:
# decoded_away_from = decoder.decode([braindata_dir+'away_from_mni.nii.gz'], 
#                                    save=braindata_dir+'away_from_decoding.txt')

In [15]:
# decoded_away_from.sort_values(decoded_away_from.columns[0], ascending=False)

In [60]:
# decoded_braindiff_d = decoder.decode([braindata_dir+'braindiff_d_mni.nii.gz'], 
#                                    save=braindata_dir+'braindiff_d_decoding.txt')

In [64]:
# decoded_braindiff_i = decoder.decode([braindata_dir+'braindiff_i_mni.nii.gz'], 
#                                    save=braindata_dir+'braindiff_i_decoding.txt')

In [9]:
# decoded_imm_del = decoder.decode([braindata_dir+'imm_del_mni.nii.gz'], 
#                                    save=braindata_dir+'imm_del_decoding.txt')

In [10]:
# decoded_del_imm = decoder.decode([braindata_dir+'del_imm_mni.nii.gz'], 
#                                    save=braindata_dir+'del_imm_decoding.txt')

In [13]:
# decoded_imm_del.sort_values(decoded_imm_del.columns[0], ascending=False)

In [14]:
# decoded_del_imm.sort_values(decoded_del_imm.columns[0], ascending=False)

In [7]:
# best remembered content overall from atlep1
decoded_a1remembered = decoder.decode([braindata_dir+'a1_mni.nii.gz'], 
                                      save=braindata_dir+'a1remembered_decoding.txt')

In [12]:
decoded_a1remembered.sort_values(decoded_a1remembered.columns[0], ascending=False)

                         ../../data/brains/a1_mni.nii.gz
dorsolateral                                      0.1593
dorsolateral prefrontal                           0.1569
dlpfc                                             0.1371
frontoparietal                                    0.1356
parietal cortex                                   0.1344
cortex dlpfc                                      0.1286
intraparietal sulcus                              0.1273
intraparietal                                     0.1251
fronto parietal                                   0.1247
working memory                                    0.1240
working                                           0.1231
task                                              0.1225
trials                                            0.1206
parietal                                          0.1202
posterior parietal                                0.1197
performance                                       0.1185
numbers                                           0.1169
prefrontal                                        0.1167
frontoparietal network                            0.1166
ips                                               0.1159
decision making                                   0.1151
executive                                         0.1151
parietal network                                  0.1133
numerical                                         0.1133
rule                                              0.1118
choice                                            0.1111
choices                                           0.1101
frontal parietal                                  0.1086
sulcus ips                                        0.1084
attentional                                       0.1077
...                                                  ...
mtg                                              -0.1250
states                                           -0.1251
acoustic                                         -0.1252
mind tom                                         -0.1259
heard                                            -0.1268
auditory cortex                                  -0.1276
gyrus stg                                        -0.1303
linguistic                                       -0.1305
primary auditory                                 -0.1335
theory mind                                      -0.1339
sts                                              -0.1350
syntactic                                        -0.1360
temporal sulcus                                  -0.1370
auditory                                         -0.1382
middle temporal                                  -0.1383
stg                                              -0.1388
spoken                                           -0.1390
sounds                                           -0.1391
speaker                                          -0.1399
sentence                                         -0.1406
language                                         -0.1418
listened                                         -0.1495
temporal                                         -0.1552
mental states                                    -0.1594
comprehension                                    -0.1633
listening                                        -0.1660
speech                                           -0.1724
superior temporal                                -0.1726
sentences                                        -0.1751
temporal gyrus                                   -0.1760

[3228 rows x 1 columns]

In [13]:
# best remembered content overall from atlep1
decoded_a1forgotten = decoder.decode([braindata_dir+'a1f_mni.nii.gz'], 
                                      save=braindata_dir+'a1forgotten_decoding.txt')

In [16]:
decoded_a1forgotten.sort_values(decoded_a1forgotten.columns[0], ascending=False)

                         ../../data/brains/a1f_mni.nii.gz
temporal gyrus                                     0.1760
sentences                                          0.1751
superior temporal                                  0.1726
speech                                             0.1724
listening                                          0.1660
comprehension                                      0.1633
mental states                                      0.1594
temporal                                           0.1552
listened                                           0.1495
language                                           0.1418
sentence                                           0.1406
speaker                                            0.1399
sounds                                             0.1391
spoken                                             0.1390
stg                                                0.1388
middle temporal                                    0.1383
auditory                                           0.1382
temporal sulcus                                    0.1370
syntactic                                          0.1360
sts                                                0.1350
theory mind                                        0.1339
primary auditory                                   0.1335
linguistic                                         0.1305
gyrus stg                                          0.1303
auditory cortex                                    0.1276
heard                                              0.1268
mind tom                                           0.1259
acoustic                                           0.1252
states                                             0.1251
mtg                                                0.1250
...                                                   ...
attentional                                       -0.1077
sulcus ips                                        -0.1084
frontal parietal                                  -0.1086
choices                                           -0.1101
choice                                            -0.1111
rule                                              -0.1118
parietal network                                  -0.1133
numerical                                         -0.1133
decision making                                   -0.1151
executive                                         -0.1151
ips                                               -0.1159
frontoparietal network                            -0.1166
prefrontal                                        -0.1167
numbers                                           -0.1169
performance                                       -0.1185
posterior parietal                                -0.1197
parietal                                          -0.1202
trials                                            -0.1206
task                                              -0.1225
working                                           -0.1231
working memory                                    -0.1240
fronto parietal                                   -0.1247
intraparietal                                     -0.1251
intraparietal sulcus                              -0.1273
cortex dlpfc                                      -0.1286
parietal cortex                                   -0.1344
frontoparietal                                    -0.1356
dlpfc                                             -0.1371
dorsolateral prefrontal                           -0.1569
dorsolateral                                      -0.1593

[3228 rows x 1 columns]

In [20]:
# best remembered content overall from atlep1
# decoded_a1diff = decoder.decode(['/Users/paxtonfitzpatrick/Desktop/a1_mni.nii.gz'], 
#                                       save=braindata_dir+'a1diff_decoding.txt')

In [36]:
# difference between good and bad memory for atlep2
decoded_a2diff = decoder.decode([braindata_dir+'braindiff_a2_mni.nii.gz'], 
                               save=braindata_dir+'a2diff_decoding.txt')

In [44]:
# difference between good and bad memory for atlep2
decoded_addiff = decoder.decode([braindata_dir+'braindiff_ad_mni.nii.gz'], 
                               save=braindata_dir+'addiff_decoding.txt')

In [45]:
decoded_addiff.sort_values(decoded_addiff.columns[0], ascending=False)

                         ../../data/brains/braindiff_ad_mni.nii.gz
default                                                     0.2473
default mode                                                0.2460
mode                                                        0.2413
mode network                                                0.2381
dmn                                                         0.2250
network dmn                                                 0.2233
state                                                       0.2128
resting                                                     0.2079
posterior cingulate                                         0.2044
resting state                                               0.2041
independent component                                       0.2022
precuneus                                                   0.1922
beliefs                                                     0.1907
ica                                                         0.1875
medial prefrontal                                           0.1874
theory mind                                                 0.1870
pcc                                                         0.1864
component ica                                               0.1862
mind                                                        0.1857
self                                                        0.1839
mental states                                               0.1819
states                                                      0.1754
theory                                                      0.1739
networks                                                    0.1701
tom                                                         0.1679
mind tom                                                    0.1675
connectivity                                                0.1658
functional connectivity                                     0.1643
cortex pcc                                                  0.1570
cortex mpfc                                                 0.1562
...                                                            ...
working                                                    -0.0995
44                                                         -0.0998
tasks                                                      -0.1016
working memory                                             -0.1024
native                                                     -0.1027
occipito temporal                                          -0.1030
demands                                                    -0.1032
chinese                                                    -0.1033
occipito                                                   -0.1042
word                                                       -0.1052
hemispheric                                                -0.1067
occipitotemporal                                           -0.1081
pseudowords                                                -0.1085
inferior temporal                                          -0.1088
hemisphere                                                 -0.1111
gyrus ifg                                                  -0.1126
verbal                                                     -0.1139
languages                                                  -0.1141
objects                                                    -0.1144
word form                                                  -0.1146
visual word                                                -0.1149
ba 44                                                      -0.1177
words                                                      -0.1179
reading                                                    -0.1194
inferior frontal                                           -0.1250
fusiform                                                   -0.1275
orthographic                                               -0.1315
fusiform gyrus                                             -0.1327
inferior                                                   -0.1431
phonological                                               -0.1441

[3228 rows x 1 columns]

In [38]:
decoded_a2diff.sort_values(decoded_a2diff.columns[0], ascending=False)

                          ../../data/brains/braindiff_a2_mni.nii.gz
precuneus                                                    0.1579
beliefs                                                      0.1544
independent component                                        0.1382
temporoparietal                                              0.1365
junction                                                     0.1338
temporoparietal junction                                     0.1334
tpj                                                          0.1319
junction tpj                                                 0.1300
networks                                                     0.1277
default mode                                                 0.1236
mode                                                         0.1220
default                                                      0.1203
network                                                      0.1173
dmn                                                          0.1131
superior frontal                                             0.1127
ica                                                          0.1125
mode network                                                 0.1123
parietal junction                                            0.1116
network dmn                                                  0.1107
component ica                                                0.1105
intentions                                                   0.1101
monitoring                                                   0.1100
thoughts                                                     0.1100
theory mind                                                  0.1096
correlates                                                   0.1092
mind tom                                                     0.1069
posterior cingulate                                          0.1063
tom                                                          0.1061
network connectivity                                         0.1050
functional networks                                          0.1030
...                                                             ...
grey                                                        -0.0646
administered                                                -0.0646
44                                                          -0.0648
phonological                                                -0.0652
diffusion                                                   -0.0654
objects                                                     -0.0659
weighted                                                    -0.0660
temporal lobe                                               -0.0664
pathways                                                    -0.0664
repeated                                                    -0.0668
tensor                                                      -0.0673
orthographic                                                -0.0680
scanned                                                     -0.0691
fusiform face                                               -0.0694
hemisphere                                                  -0.0696
dementia                                                    -0.0697
anatomical                                                  -0.0701
face ffa                                                    -0.0713
fasciculus                                                  -0.0727
mtl                                                         -0.0727
anterior temporal                                           -0.0732
faces                                                       -0.0749
lesion                                                      -0.0800
face                                                        -0.0806
inferior temporal                                           -0.0818
pseudowords                                                 -0.0852
fusiform gyrus                                              -0.0863
longitudinal                                                -0.0881
fusiform                                                    -0.0897
fiber                                                       -0.0935

[3228 rows x 1 columns]

In [41]:
braindiff_d_decoded = pd.read_csv(braindata_dir+'braindiff_d_decoding.txt')
braindiff_i_decoded = pd.read_csv(braindata_dir+'braindiff_i_decoding.txt')

In [43]:
braindiff_d_decoded.sort_values(braindiff_d_decoded.columns[1], ascending=False)

                       Feature  ../../data/brains/braindiff_d_mni.nii.gz
2242                 precuneus                                    0.2058
733               default mode                                    0.1953
732                    default                                    0.1943
1831              mode network                                    0.1936
2217       posterior cingulate                                    0.1929
1830                      mode                                    0.1888
869                        dmn                                    0.1864
1927               network dmn                                    0.1848
318                    beliefs                                    0.1836
2786                     state                                    0.1775
2977               theory mind                                    0.1768
1765         medial prefrontal                                    0.1760
1443     independent component                                    0.1740
2530                   resting                                    0.1674
2127                       pcc                                    0.1674
2531             resting state                                    0.1667
1819                      mind                                    0.1632
2999                       tom                                    0.1596
1820                  mind tom                                    0.1585
2958           temporoparietal                                    0.1576
1791             mental states                                    0.1570
2959  temporoparietal junction                                    0.1558
2976                    theory                                    0.1517
2732                    social                                    0.1496
3009                       tpj                                    0.1477
2618                      self                                    0.1466
658                 cortex pcc                                    0.1459
1760                    medial                                    0.1440
662           cortex precuneus                                    0.1433
2088         parietal junction                                    0.1424
...                        ...                                       ...
1900                    native                                   -0.0895
3210            working memory                                   -0.0904
3144                    visual                                   -0.0905
1554                  involved                                   -0.0908
2046              orthographic                                   -0.0912
1334                hemisphere                                   -0.0914
748                    demands                                   -0.0915
415                    chinese                                   -0.0929
2800                   stimuli                                   -0.0933
3118          ventral premotor                                   -0.0934
229                 arithmetic                                   -0.0937
2802                  stimulus                                   -0.0939
1560                       ips                                   -0.0946
1980                    object                                   -0.0959
2872                sulcus ips                                   -0.0968
1466                  inferior                                   -0.0974
1851                    monkey                                   -0.0977
1336               hemispheric                                   -0.0980
1978                 numerical                                   -0.0998
2667                     shape                                   -0.1009
2001         occipito temporal                                   -0.1009
1731                  matching                                   -0.1019
2163              phonological                                   -0.1032
2000                  occipito                                   -0.1033
2935                     tasks                                   -0.1038
2338               pseudowords                                   -0.1044
364                calculation                                   -0.1056
1984                   objects                                   -0.1089
1538             intraparietal                                   -0.1117
1539      intraparietal sulcus                                   -0.1156

[3228 rows x 2 columns]

In [42]:
braindiff_i_decoded.sort_values(braindiff_i_decoded.columns[1], ascending=False)

                       Feature  ../../data/brains/braindiff_i_mni.nii.gz
2242                 precuneus                                    0.2064
733               default mode                                    0.2022
732                    default                                    0.2013
1831              mode network                                    0.2009
2217       posterior cingulate                                    0.1989
1830                      mode                                    0.1954
869                        dmn                                    0.1931
1927               network dmn                                    0.1917
318                    beliefs                                    0.1877
2786                     state                                    0.1860
2977               theory mind                                    0.1849
1765         medial prefrontal                                    0.1823
1443     independent component                                    0.1784
2530                   resting                                    0.1749
2531             resting state                                    0.1740
2127                       pcc                                    0.1731
1819                      mind                                    0.1714
2999                       tom                                    0.1665
1791             mental states                                    0.1657
1820                  mind tom                                    0.1654
2958           temporoparietal                                    0.1605
2959  temporoparietal junction                                    0.1588
2976                    theory                                    0.1583
2732                    social                                    0.1544
2618                      self                                    0.1524
658                 cortex pcc                                    0.1510
3009                       tpj                                    0.1500
1760                    medial                                    0.1484
655                cortex mpfc                                    0.1466
2088         parietal junction                                    0.1463
...                        ...                                       ...
2136                perceptual                                   -0.0944
2046              orthographic                                   -0.0948
1609         lateral occipital                                   -0.0950
3118          ventral premotor                                   -0.0956
748                    demands                                   -0.0956
3209                   working                                   -0.0957
415                    chinese                                   -0.0961
2800                   stimuli                                   -0.0968
229                 arithmetic                                   -0.0980
3210            working memory                                   -0.0982
1336               hemispheric                                   -0.0992
3144                    visual                                   -0.0992
2802                  stimulus                                   -0.0996
1851                    monkey                                   -0.1004
1466                  inferior                                   -0.1004
1560                       ips                                   -0.1035
2163              phonological                                   -0.1042
2338               pseudowords                                   -0.1044
1980                    object                                   -0.1046
2872                sulcus ips                                   -0.1055
1978                 numerical                                   -0.1066
1731                  matching                                   -0.1068
2001         occipito temporal                                   -0.1085
2667                     shape                                   -0.1090
2935                     tasks                                   -0.1106
2000                  occipito                                   -0.1108
364                calculation                                   -0.1123
1984                   objects                                   -0.1170
1538             intraparietal                                   -0.1213
1539      intraparietal sulcus                                   -0.1254

[3228 rows x 2 columns]

In [23]:
away_from_terms = pd.read_csv(braindata_dir+'away_from_decoding.txt')

In [28]:
test = away_from_terms.sort_values(away_from_terms.columns[1], ascending=False)

In [30]:
test.loc[test[test.columns[1]]> 0]

                     Feature  ../../data/brains/away_from_mni.nii.gz
2771                  speech                                  0.2134
1659               listening                                  0.1875
2639               sentences                                  0.1839
1592                language                                  0.1833
2881       superior temporal                                  0.1806
272                 auditory                                  0.1735
2946          temporal gyrus                                  0.1714
2773       speech production                                  0.1706
2779                  spoken                                  0.1671
2796                     stg                                  0.1619
496            comprehension                                  0.1609
1658                listened                                  0.1598
3166                   vocal                                  0.1592
2757                 speaker                                  0.1569
2314              production                                  0.1547
2745                  sounds                                  0.1545
2772       speech perception                                  0.1533
273          auditory cortex                                  0.1524
1652              linguistic                                  0.1519
86                  acoustic                                  0.1517
1302               gyrus stg                                  0.1506
2905               syntactic                                  0.1479
2285        primary auditory                                  0.1454
2637                sentence                                  0.1441
1593  language comprehension                                  0.1425
359                    broca                                  0.1399
1327                   heard                                  0.1384
2941                temporal                                  0.1383
2174                  planum                                  0.1359
3167                   voice                                  0.1358
...                      ...                                     ...
2950      temporal occipital                                  0.0009
1911         negative affect                                  0.0009
2702                  simple                                  0.0009
2940               tegmental                                  0.0009
3175              voxel wise                                  0.0008
2337               providing                                  0.0008
2448                 relates                                  0.0007
2181                 playing                                  0.0007
2020                  online                                  0.0007
1432              incidental                                  0.0006
112                addressed                                  0.0006
2134                 percept                                  0.0006
2847                subserve                                  0.0006
1123                 factors                                  0.0006
1545                invasive                                  0.0005
2893             surrounding                                  0.0005
796               difference                                  0.0005
2447                  relate                                  0.0005
2781                  stable                                  0.0004
2476                repeated                                  0.0004
2385               reactions                                  0.0003
3183                    ways                                  0.0002
1249                generate                                  0.0002
972                  enabled                                  0.0002
2926            task induced                                  0.0001
2118      pathophysiological                                  0.0001
1575                judgment                                  0.0001
2192                  poorer                                  0.0001
228                    arise                                  0.0001
552             considerable                                  0.0001

[1400 rows x 2 columns]