In [1]:
import numpy as np
import pandas as pd
import json
import time
import datetime
import calendar

In [2]:
# load in psiturk data
rm1df = pd.read_json('../../data/db/exported/room1-2.8.19.json', convert_dates=['beginhit','endhit'])
rm2df = pd.read_json('../../data/db/exported/room2-2.8.19.json', convert_dates=['beginhit','endhit'])

# drop runs that didn't finish
rm1df = rm1df[rm1df.status != 1]
rm2df = rm2df[rm2df.status != 1]

# keep relevant columns
rm1df = rm1df[['uniqueid','datastring','beginhit','endhit','hitid','status']].reset_index(drop=True)
rm2df = rm2df[['uniqueid','datastring','beginhit','endhit','hitid','status']].reset_index(drop=True)

# format datastring as dict 
rm1df['datastring'] = rm1df['datastring'].apply(json.loads)
rm2df['datastring'] = rm2df['datastring'].apply(json.loads)

# add test room column
rm1df['testroom'] = 1
rm2df['testroom'] = 2

# remove test runs for each room
rm1df = rm1df.loc[1:].reset_index(drop=True)
rm2df = rm2df.loc[1:].reset_index(drop=True)

# concatenate dataframes
expdf = pd.concat([rm1df, rm2df], ignore_index=True)

In [3]:
# load pre/post questionnaire responses
preqdf = pd.read_csv('../../data/google-form-data/Pre-experiment Questionnaire.csv', parse_dates=[0])
preqdf = preqdf.rename(index=str, columns={'Timestamp':'preqtime'})
postqdf = pd.read_csv('../../data/google-form-data/Post-experiment questionnaire.csv', parse_dates=[0])
postqdf = postqdf.rename(index=str, columns={'Timestamp':'postqtime'})

# exclude test runs
preqdf = preqdf.dropna(subset=['Subject ID'], inplace=False).reset_index(drop=True)
postqdf = postqdf.dropna(subset=['Subject ID'], inplace=False).reset_index(drop=True)

In [4]:
# convert form timestamp to POSIX time **SERIES.APPLY(DT.DT.TIMESTAMP).MULTIPLY(1000) DOES NOT WORK**
newpretimestamp = pd.Series([0]*len(preqdf['preqtime']))
for ix, val in enumerate(newpretimestamp):
    newpretimestamp[ix] = preqdf['preqtime'][ix].timestamp()*1000
preqdf['preqtime'] = newpretimestamp

newposttimestamp = pd.Series([0]*len(postqdf['postqtime']))
for ix, val in enumerate(newposttimestamp):
    newposttimestamp[ix] = postqdf['postqtime'][ix].timestamp()*1000
postqdf['postqtime'] = newposttimestamp

In [5]:
# remove dropped subjects from google form and experiment dfs
dropids = ['MD-102218-B-04','MD-020119-A-01','MD-102318-A-01','MD-101318-A-05','MD-1011318-A-05','MD-020119-B-01',
          'MD-101218-B-04']

for dropid in dropids:
    preqdf = preqdf[preqdf['Subject ID'] != dropid]
    postqdf = postqdf[postqdf['Subject ID'] != dropid]
        
preqdf.reset_index(drop=True, inplace=True)
postqdf.reset_index(drop=True, inplace=True)

# drop a 
expdf = expdf.loc[1:].reset_index(drop=True)

In [6]:
# fix mistaken day/repeat ID assignments

preqdf.at[76,'Subject ID'] = 'MD-102018-A-03'
postqdf.at[76,'Subject ID'] = 'MD-102018-A-03'

preqdf.at[77,'Subject ID'] = 'MD-102218-A-06'
postqdf.at[77,'Subject ID'] = 'MD-102218-A-06'

preqdf.at[85,'Subject ID'] = 'MD-102218-B-06'
postqdf.at[85,'Subject ID'] = 'MD-102218-B-06'

preqdf.at[89,'Subject ID'] = 'MD-013119-A-02'
postqdf.at[90,'Subject ID'] = 'MD-013119-A-02'

### for mapping between Google Forms with experiment IDs and SQLite databases with PsiTurk IDs

In [7]:
# add empty columns from pre/postquestionnaires to expdf
newcols = pd.unique(np.concatenate([i.columns.values for i in [preqdf,postqdf]]))
expdf = pd.concat([expdf, pd.DataFrame(columns=newcols)], sort=False)

turktimes = {}
preqtimes = {}
mapped = []

# get psiturk start times
for ix, sub in expdf.iterrows():
    turktimes[sub['datastring']['data'][0]['dateTime']] = ix
# get gform submit times
for ix, sub in preqdf.iterrows():
    preqtimes[sub['preqtime']] = ix

# for each psiturk time, find row with closest gform submission time
for turktime, rownum in turktimes.items():
    closest = preqtimes.get(turktime, preqtimes[min(preqtimes.keys(), key=lambda k: abs(k-turktime))])
#     print(datetime.datetime.fromtimestamp(turktime/1e3))
#     print(datetime.datetime.fromtimestamp(preqdf.loc[closest]['preqtime'] / 1e3))
#     print('\n\n')
#     print((turktime - preqdf.loc[closest]['preqtime'])/60000 , closest)
#     if closest in mapped:
#         print(str(closest) + ' already there')
#     else:
#         mapped.append(closest)

In [7]:
preqdf

,preqtime,Subject ID,"Outside of this study, have you ever watched an episode of either of the TV shows ""Atlanta"" or ""Arrested Development?""",Is English your first language?,Do you have any hearing or speech impairments?,Do you have normal color vision?,"Are you taking any medications or have you had any recent injuries that could affect your memory or attention? (if so, describe below)","If yes above, describe",In what year were you born?,Sex,Ethnicity,Race (check all that apply),Highest Degree Achieved,"If you are currently an undergraduate, what year are you?",What is/was your major?,How many hours of sleep did you get last night?,How many cups of coffee have you had today?,How alert are you feeling?
0,1539364543000,MD-101218-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,White,Some high school,'22,undeclared,7.0,1.0,A little alert
1,1539368333000,MD-101218-B-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,5.0,0.0,A little sluggish
2,1539368938000,MD-101218-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,White,Some college,'22,undeclared,7.0,2.0,A little alert
3,1539372202000,MD-101218-B-02,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,American Indian or Alaska Native;White,Some college,'22,neuroscience,9.0,0.0,A little alert
4,1539372686000,MD-101218-A-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,Asian,High school graduate,'22,Sociology,7.0,0.0,A little alert
5,1539376148000,MD-101218-B-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,Some college,'22,undeclared,8.0,0.0,A little alert
6,1539376344000,MD-101218-A-04,I've never watched either one,Yes,No,Yes,Yes,Concussion (April 2015),1999,Female,Not Hispanic or Latino,White,Some college,'22,Undeclared (but planning on being a psychology...,8.0,1.0,Very sluggish
7,1539451793000,MD-101318-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Black or African American;White,Some college,'22,undeclared,8.0,0.0,A little alert
8,1539452101000,MD-101318-B-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'22,Undeclared,7.0,2.0,Neutral
9,1539455818000,MD-101318-B-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,NaN,Not Hispanic or Latino,Asian,High school graduate,'22,Psychology,6.0,1.0,Neutral
10,1539455969000,MD-101318-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian,Some college,'21,Biology,7.0,0.0,Neutral
11,1539459062000,MD-101318-A-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,8.0,0.0,A little alert
12,1539459522000,MD-101318-B-03,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian,Some college,'21,Undeclared,6.0,0.0,Neutral
13,1539462969000,MD-101318-A-04,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Hispanic or Latino,White,High school graduate,'22,Neuroscience,7.0,0.0,Neutral
14,1539463615000,MD-101318-B-04,I've never watched either one,Yes,No,Yes,No,NaN,1998,Male,Not Hispanic or Latino,White,Some college,'21,Economics/Neuroscience,11.0,0.0,A little alert
15,1539466698000,MD-101318-B-05,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian,High school graduate,'22,undeclared,8.0,0.0,A little alert
16,1539470171000,MD-101318-A-06,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian,High school graduate,'21,undeclared,7.0,0.0,A little alert
17,1539471641000,MD-101318-B-06,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian,High school graduate,'21,Undeclared,9.5,1.0,Very alert
18,1539711879000,MD-101618-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,White,High school graduate,'22,Engineering,10.0,0.0,A little alert
19,1539715119000,MD-101618-B-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,Some college,'22,undeclared,6.0,0.0,A little sluggish
20,1539715501000,MD-101618-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1998,Male,Not Hispanic or Latino,Asian,Some college,'20,Anthropology,9.0,1.0,Very alert
21,1539719043000,MD-101618-B-02,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,engineering,5.0,1.0,Neutral
22,1539719320000,MD-101618-A-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Asian,Some college,'22,undeclared,7.0,0.0,Very alert
23,1539722565000,MD-101618-B-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Asian,High school graduate,'22,neuroscience,6.0,0.0,A little sluggish
24,1539726799000,MD-101618-A-04,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Hispanic or Latino,White,Some college,'22,undeclared,10.0,0.0,Neutral
25,1539727223000,MD-101618-B-04,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,7.0,0.0,A little sluggish
26,1539870845000,MD-101218-A-03,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,Asian,High school graduate,'22,Sociology,8.0,0.0,A little alert
27,1539879105000,MD-101218-B-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,7.0,0.0,A little alert
28,1539879752000,MD-101218-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,White,Some college,'22,Undeclared,6.0,2.0,Neutral
29,1539889302000,MD-101218-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,White,Some high school,'22,undeclared,9.0,1.0,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,1540757664000,MD-102018-A-03,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'20,anthropology & global health,7.0,0.0,Neutral
77,1540760898000,MD-102218-A-06,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Asian,High school graduate,'22,Undeclared,6.0,0.0,Neutral
78,1540761686000,MD-102018-A-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'22,undeclared,5.0,0.0,A little alert
79,1540765989000,MD-102018-A-02,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,7.0,1.0,Neutral
80,1540823076000,MD-102218-B-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,6.0,1.0,A little sluggish
81,1540838074000,MD-102218-B-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,NaN,White,Some college,'22,undeclared,8.0,1.0,A little alert
82,1540838890000,MD-102218-B-05,I've never watched either one,Yes,No,Yes,No,NaN,2000,Male,Not Hispanic or Latino,White,High school graduate,'22,Undeclared,7.0,0.0,Neutral
83,1540842562000,MD-102218-A-04,I've never watched either one,Yes,No,Yes,No,NaN,1998,Female,Not Hispanic or Latino,Asian,Some college,'20,Neuroscience,8.0,1.0,Very sluggish
84,1540843288000,MD-102218-B-03,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,High school graduate,'22,undeclared,6.0,0.0,Neutral
85,1540846804000,MD-102218-B-06,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,White,Some college,'22,undeclared,9.0,1.0,Very alert
86,1540854870000,MD-102218-A-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'22,undeclared,6.0,1.0,A little sluggish
87,1540856114000,MD-102218-A-07,I've never watched either one,Yes,No,Yes,No,NaN,1998,Female,Not Hispanic or Latino,Asian,Some college,'20,Environmental Studies and Neuroscience,8.0,1.0,A little alert
88,1548963430000,MD-013119-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Asian,High school graduate,'22,undeclared,7.0,0.0,A little alert
89,1548975741000,MD-013119-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,Asian,High school graduate,'21,computer science,8.0,0.0,Neutral
90,1548975832000,MD-013119-B-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Black or African American;White,Some college,'21,Psychology,6.0,1.0,Neutral
91,1549048493000,MD-020119-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1997,Female,Not Hispanic or Latino,White,Some college,'19,Economics modified with Neuroscience,7.0,2.0,A little sluggish
92,1549052604000,MD-020119-B-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'21,Psychology and Film,8.0,0.0,A little sluggish
93,1549052726000,MD-020119-A-03,I've never watched either one,Yes,No,Yes,No,NaN,1996,Female,Not Hispanic or Latino,Asian,Some college,'19,Engineering,5.0,0.0,Neutral
94,1549056633000,MD-020119-B-03,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,White,High school graduate,'22,Latin Literature and Neuroscience,9.0,1.0,Very alert
95,1549061426000,MD-020119-A-04,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Black or African American,High school graduate,'22,Undeclared,6.5,0.0,A little sluggish
96,1549494108000,MD-013119-B-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Black or African American;White,Some college,'21,psychology,7.0,2.0,Neutral
97,1549557988000,MD-020119-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1997,Female,Not Hispanic or Latino,White,Some college,'19,Economics mod with Neuroscience,10.0,1.0,Neutral
98,1549567890000,MD-013119-A-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Asian,High school graduate,'22,undeclared,6.0,0.0,Neutral
99,1549568191000,MD-020119-A-03,I've never watched either one,Yes,No,Yes,No,NaN,1996,Female,Not Hispanic or Latino,Asian,Some college,'19,Engineering,7.5,0.0,Neutral
100,1549575310000,MD-020719-B-01,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,Asian;White,Some college,'22,undeclared,7.0,0.0,A little sluggish
101,1549575805000,MD-020119-B-03,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,White,High school graduate,'22,Latin Literature and Neuroscience,7.0,1.0,Very alert
102,1549580497000,MD-013119-A-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Male,Not Hispanic or Latino,Asian,High school graduate,'21,CS mod neuro,9.0,0.0,A little alert
103,1549639074000,MD-020119-A-04,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Black or African American,High school graduate,'22,Undeclared,6.0,0.0,Neutral
104,1549653467000,MD-020819-B-01,I've never watched either one,Yes,No,Yes,No,NaN,2000,Female,Not Hispanic or Latino,Black or African American,High school graduate,'22,Undeclared,5.0,0.0,Neutral
105,1549657276000,MD-020119-B-02,I've never watched either one,Yes,No,Yes,No,NaN,1999,Female,Not Hispanic or Latino,White,Some college,'21,Film and Psychology,8.0,0.0,A little sluggish

In [8]:
postqdf

,postqtime,Subject ID,How engaging did you find the episode?,How easy/difficult was it to follow the episode?,How well do you feel you recalled the events of the episode?,How well do you feel you learned the characters' names over the course of the episode?,How tired do you feel?
0,1539367920000,MD-101218-A-01,Very engaging,Somewhat easy,Very well,Very well,A little tired
1,1539371395000,MD-101218-B-01,A little engaging,Somewhat easy,Very well,Somewhat well,A little tired
2,1539371970000,MD-101218-A-02,Very engaging,Somewhat easy,Somewhat well,Somewhat well,A little tired
3,1539374968000,MD-101218-B-02,Very engaging,Very easy,Very well,Somewhat well,A little alert
4,1539375514000,MD-101218-A-03,Very engaging,Somewhat easy,Very well,Somewhat well,Very alert
5,1539378961000,MD-101218-B-03,A little engaging,Somewhat easy,Neutral,Neutral,Neutral
6,1539379335000,MD-101218-A-04,Very engaging,Neutral,Somewhat well,Not very well,A little tired
7,1539454508000,MD-101318-A-01,A little engaging,Neutral,Neutral,Neutral,Neutral
8,1539455459000,MD-101318-B-01,Very engaging,Somewhat easy,Somewhat well,Somewhat well,Very alert
9,1539458649000,MD-101318-A-02,Very engaging,Somewhat easy,Somewhat well,Somewhat well,A little tired
10,1539459154000,MD-101318-B-02,Very engaging,Somewhat easy,Somewhat well,Not very well,A little tired
11,1539462098000,MD-101318-A-03,A little engaging,Somewhat easy,Somewhat well,Not very well,Neutral
12,1539462452000,MD-101318-B-03,Very engaging,Somewhat easy,Very well,Somewhat well,Neutral
13,1539465900000,MD-101318-A-04,Very engaging,Somewhat easy,Neutral,Somewhat well,Neutral
14,1539466482000,MD-101318-B-04,A little engaging,Neutral,Somewhat well,Not very well,Neutral
15,1539470268000,MD-101318-B-05,A little engaging,Somewhat easy,Very well,Somewhat well,Neutral
16,1539473279000,MD-101318-A-06,Very engaging,Somewhat easy,Somewhat well,Very well,Neutral
17,1539474554000,MD-101318-B-06,Very engaging,Somewhat easy,Somewhat well,Neutral,A little tired
18,1539714625000,MD-101618-A-01,Very engaging,Somewhat easy,Very well,Somewhat well,A little alert
19,1539718257000,MD-101618-B-01,Very engaging,Somewhat difficult,Somewhat well,Somewhat well,A little tired
20,1539718570000,MD-101618-A-02,Very engaging,Very easy,Very well,Somewhat well,A little alert
21,1539722159000,MD-101618-B-02,A little engaging,Somewhat easy,Somewhat well,Neutral,A little tired
22,1539722371000,MD-101618-A-03,Very engaging,Somewhat easy,Neutral,Somewhat well,Very alert
23,1539725159000,MD-101618-B-03,Very engaging,Neutral,Not very well,Not well at all,A little tired
24,1539729611000,MD-101618-A-04,A little engaging,Somewhat easy,Somewhat well,Somewhat well,Neutral
25,1539729913000,MD-101618-B-04,Very engaging,Very easy,Very well,Very well,Neutral
26,1539874542000,MD-101218-A-03,Very engaging,Very easy,Somewhat well,Somewhat well,A little alert
27,1539882434000,MD-101218-B-01,A little boring,Very easy,Neutral,Not very well,A little tired
28,1539882960000,MD-101218-A-02,Very engaging,Very easy,Somewhat well,Not very well,A little tired
29,1539892517000,MD-101218-A-01,A little engaging,Very easy,Somewhat well,Very well,A little tired
...,...,...,...,...,...,...,...
76,1540760734000,MD-102018-A-03,A little engaging,Neutral,Somewhat well,Somewhat well,Neutral
77,1540764333000,MD-102218-A-06,A little engaging,Neutral,Not very well,Not very well,Neutral
78,1540765225000,MD-102018-A-01,A little engaging,Somewhat easy,Not very well,Not very well,A little tired
79,1540768978000,MD-102018-A-02,Very engaging,Somewhat easy,Neutral,Somewhat well,A little tired
80,1540825829000,MD-102218-B-01,A little engaging,Somewhat difficult,Somewhat well,Very well,A little tired
81,1540840929000,MD-102218-B-02,Very engaging,Neutral,Somewhat well,Very well,A little tired
82,1540842232000,MD-102218-B-05,A little engaging,Very easy,Very well,Very well,Neutral
83,1540845675000,MD-102218-A-04,A little engaging,Somewhat difficult,Not very well,Somewhat well,Very tired
84,1540846596000,MD-102218-B-03,A little engaging,Somewhat easy,Somewhat well,Neutral,Neutral
85,1540849516000,MD-102218-B-06,Very engaging,Somewhat easy,Somewhat well,Somewhat well,Neutral
86,1540858225000,MD-102218-A-01,A little engaging,Somewhat easy,Not very well,Not very well,Very tired
87,1540859059000,MD-102218-A-07,Very engaging,Somewhat difficult,Neutral,Very well,A little tired
88,1548966981000,MD-013119-A-01,A little engaging,Very easy,Very well,Somewhat well,A little tired
89,1548979191000,MD-013119-B-01,Very engaging,Very easy,Somewhat well,Somewhat well,Neutral
90,1548979238000,MD-013119-A-02,Very engaging,Very easy,Somewhat well,Somewhat well,Very alert
91,1549051376000,MD-020119-A-02,Very engaging,Somewhat difficult,Very well,Neutral,A little alert
92,1549055443000,MD-020119-B-02,A little engaging,Very easy,Somewhat well,Very well,A little tired
93,1549055936000,MD-020119-A-03,A little engaging,Very easy,Somewhat well,Somewhat well,A little tired
94,1549059569000,MD-020119-B-03,Very engaging,Somewhat easy,Very well,Very well,A little tired
95,1549064998000,MD-020119-A-04,Very engaging,Somewhat easy,Somewhat well,Somewhat well,A little alert
96,1549497723000,MD-013119-B-01,A little boring,Somewhat difficult,Neutral,Somewhat well,A little tired
97,1549560835000,MD-020119-A-02,Very engaging,Somewhat easy,Neutral,Neutral,A little tired
98,1549571623000,MD-020119-A-03,A little engaging,Somewhat easy,Somewhat well,Very well,Very tired
99,1549572300000,MD-013119-A-01,A little engaging,Somewhat easy,Neutral,Not very well,Very tired
100,1549577943000,MD-020719-B-01,Very engaging,Somewhat easy,Very well,Neutral,A little tired
101,1549578629000,MD-020119-B-03,A little engaging,Somewhat difficult,Not very well,Not well at all,Very alert
102,1549583557000,MD-013119-A-02,A little engaging,Very easy,Somewhat well,Somewhat well,Neutral
103,1549642842000,MD-020119-A-04,A little engaging,Neutral,Somewhat well,Neutral,Neutral
104,1549656982000,MD-020819-B-01,Very engaging,Very easy,Very well,Somewhat well,A little tired
105,1549660756000,MD-020119-B-02,Very engaging,Very easy,Somewhat well,Very well,A little tired

In [9]:
expdf

,uniqueid,datastring,beginhit,endhit,hitid,status,testroom
0,debugBUnNA:debugLtZcs,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 19:17:03.503575,2018-10-12 20:10:44.883411,debugTkKFp,3,1
1,debugd1YD1:debug4FrAg,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 20:22:07.319435,2018-10-12 21:09:46.566325,debugonOYk,3,1
2,debugGaDml:debugFTHoY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 21:28:01.305584,2018-10-12 22:16:31.057617,debugXHY6O,3,1
3,debugGVTD3:debugfpzCT,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-12 22:59:26.829625,2018-10-13 00:01:24.711451,debuggQ0y6,3,1
4,debugokLIG:debugalG88,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 18:28:34.378931,2018-10-13 19:15:12.977411,debugslG65,3,1
5,debugdhnfF:debug6fW93,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 19:35:43.889748,2018-10-13 20:32:37.663906,debugszpCm,3,1
6,debugHKLdw:debugk43rK,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 20:37:43.034617,2018-10-13 21:27:38.367721,debugHGwAN,3,1
7,debugnj3ww:debugAC3on,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 21:34:31.560211,2018-10-13 22:25:03.538624,debughqOmP,3,1
8,debugmRWSb:debugPVXlB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 22:36:59.470450,2018-10-13 23:39:04.416342,debugKyt7W,3,1
9,debug3lixg:debugdwpeu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-13 23:58:52.853801,2018-10-14 00:49:19.357875,debugNPCaa,3,1
10,debugSlGFs:debug42TAZ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 18:43:23.919675,2018-10-16 19:31:09.744949,debugRDfe2,3,1
11,debughbxU4:debugUuTk6,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 19:37:20.607109,2018-10-16 20:31:04.663568,debugQDztf,3,1
12,debugPWYYp:debugg9K3I,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 20:42:29.538168,2018-10-16 21:36:28.945087,debugy6cu7,3,1
13,debugjQumg:debugSascw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 21:41:44.047611,2018-10-16 22:26:05.159753,debugZFxnA,3,1
14,debugScfXr:debugJN6fA,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-16 22:50:21.145527,2018-10-16 23:40:16.082236,debugCYT72,3,1
15,debugIFCgX:debugt0bgV,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 14:52:24.425282,2018-10-18 15:55:52.788902,debugD7OMi,3,1
16,debugQEynG:debugpwxCU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 17:09:47.721500,2018-10-18 18:07:19.944406,debugzSZgD,3,1
17,debug2Ea7T:debugosNZ7,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 20:00:26.949390,2018-10-18 20:55:26.773396,debugrWVJB,3,1
18,debugBB0yq:debug30NBt,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-18 23:36:47.846224,2018-10-19 00:26:44.282091,debugPQRfi,3,1
19,debugxH6Hc:debughncuB,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 15:32:31.479807,2018-10-19 16:28:34.059428,debugGs8jX,3,1
20,debugbu5Bq:debugl91xD,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:30:28.663944,2018-10-19 19:16:44.987548,debugsjD9k,3,1
21,debugBhGxH:debugMWNLW,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 19:25:39.134717,2018-10-19 20:14:01.652563,debugAVKcW,3,1
22,debug6GN7B:debugBfGog,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:42:41.578907,2018-10-19 21:30:58.820248,debugU0uFZ,3,1
23,debug5vYxL:debug5nmdy,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 22:45:49.525782,2018-10-19 23:34:17.974753,debugt5ypJ,3,1
24,debugdHg9G:debugnb698,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 16:57:14.178075,2018-10-20 17:55:32.458968,debugUD0ms,3,1
25,debugXxDJj:debugwfW5a,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:11:07.473360,2018-10-20 20:01:31.411971,debugII2Xo,3,1
26,debugTFgpv:debugfK2JN,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:15:28.823106,2018-10-20 21:15:33.010013,debug8lbdL,3,1
27,debugVFMcA:debugjM9rk,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:22:30.703964,2018-10-20 22:18:55.936915,debugaz6TP,3,1
28,debugjuwsg:debug3pWiZ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 22:34:15.759703,2018-10-20 23:33:57.663137,debugKrfpr,3,1
29,debugqWZVC:debugZSccI,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 15:42:09.400278,2018-10-22 16:37:25.142308,debugWzwft,3,1
...,...,...,...,...,...,...,...
76,debugb8Mbo:debugWMuG3,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 18:31:19.601051,2018-10-19 19:18:53.588909,debugiEYko,3,2
77,debugVzPKf:debugbR0Vq,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-19 20:23:06.091565,2018-10-19 21:29:39.493564,debugol7OU,3,2
78,debugS5d5Q:debugpxU3l,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 17:11:15.010873,2018-10-20 18:01:28.914321,debugqqX98,3,2
79,debugNTcAd:debugiaabY,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 18:05:56.447266,2018-10-20 18:56:08.578210,debugJkXTc,3,2
80,debugVmS30:debugTvoFz,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 19:19:01.036352,2018-10-20 20:16:08.648875,debugKZIcf,3,2
81,debugmfo3M:debugCN3Vj,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 20:20:51.861989,2018-10-20 21:14:59.556348,debugqh216,3,2
82,debugRNwge:debugv0fyi,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-20 21:28:28.792497,2018-10-20 22:17:39.967758,debug0L0Oy,3,2
83,debugfO0us:debug6tlz1,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-21 23:19:44.803432,2018-10-22 00:23:24.515902,debugrctlv,3,2
84,debugLou4K:debug5KpMQ,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 16:51:53.390057,2018-10-22 17:40:58.713683,debugsx10t,3,2
85,debuglAycr:debugoFV0D,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 18:13:19.729907,2018-10-22 19:09:59.702632,debugNgrtk,3,2
86,debugHNBk3:debugUUMPo,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 19:17:01.779509,2018-10-22 20:07:04.697452,debugdWWks,3,2
87,debugohSU7:debugRz3rh,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 20:31:44.881569,2018-10-22 21:38:05.206211,debugOWRjW,3,2
88,debug67jbC:debugFuOd5,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 22:23:42.681643,2018-10-22 23:08:59.861848,debugCMbxH,3,2
89,debugWvhTI:debug65Thd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-22 23:24:13.194309,2018-10-23 00:13:22.782005,debugJF0Wp,3,2
90,debugm7zD9:debugOLIFw,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 18:30:23.839666,2018-10-23 19:29:36.654793,debugf5gky,3,2
91,debugW3qVn:debugxspIb,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 19:42:51.543476,2018-10-23 20:45:55.867094,debugXjUBt,3,2
92,debug89P9i:debugM6pZC,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 20:52:09.380476,2018-10-23 21:51:15.973999,debugTCRGh,3,2
93,debugTYPE4:debugnAJ5U,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-23 22:58:02.839931,2018-10-23 23:49:14.143795,debugRG2lh,3,2
94,debugoAeJs:debug47jDd,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 16:34:32.511568,2018-10-28 17:52:26.238551,debugKK0U7,3,2
95,debugAlono:debugbY9Uu,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 19:55:23.218881,2018-10-28 20:50:23.398119,debugGBOki,3,2
96,debugYsNkJ:debug0AYus,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 22:06:57.545411,2018-10-28 23:05:44.007621,debug2D5mC,3,2
97,debugVk1WF:debugksIUE,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-28 23:32:03.505549,2018-10-29 00:23:09.765200,debugBgmvn,3,2
98,debugFL4Kc:debugPi0it,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 19:33:26.698755,2018-10-29 20:22:25.611807,debugbe5SC,3,2
99,debugAN3bL:debugJClT8,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-29 20:47:52.256760,2018-10-29 21:41:34.312890,debugs4E6X,3,2
100,debugTkyN6:debugdsr6W,"{'condition': 0, 'counterbalance': 0, 'assignm...",2018-10-30 00:34:19.043260,2018-10-30 01:24:36.564559,debugMdey9,3,2
101,debug5ytRS:debug22nvn,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-01-31 23:01:12.170466,2019-02-01 00:00:58.271323,debughWKN0,3,2
102,debugRQQWb:debugwDi2H,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 20:24:04.448255,2019-02-01 21:19:38.414725,debugU0Ils,3,2
103,debugo1MpX:debugfpXYH,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-01 22:48:31.811536,2019-02-01 23:50:55.654008,debugnMToQ,3,2
104,debugSeRNG:debug5pTo9,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 19:29:32.573721,2019-02-07 20:45:06.517044,debugvKGyP,3,2
105,debug41SJm:debugJW4AU,"{'condition': 0, 'counterbalance': 0, 'assignm...",2019-02-07 21:42:17.424466,2019-02-07 22:30:42.922183,debugWs4e3,3,2